### ISSUE TITLE
No such file or directory: 'data/resources/Task1-VQAnswering2021-Test-ReferenceAnswers_mscoco_format_vqa.json

### ISSUE THREAD

**Issue by huanhuan414** [abachaa/VQA-Med-2021#1]
"No such file or directory: 'data/resources/Task1-VQAnswering2021-Test-ReferenceAnswers_mscoco_format_vqa.json" when I run  VQA-Med-2021--VQA--Evaluator.py . so where can I get this json file?

**Comment by abachaa** [comment]
https://github.com/abachaa/VQA-Med-2021/tree/main/EvaluationCode/data/resources
